/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Tugas_BAB4;

import Tugas_BAB4.*;

/**
 *
 * @author user
 */
public class GUI_Kelahiran extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Sistem_Data_Kelahiran
     */
   public GUI_Kelahiran() {
    initComponents();
    setLocationRelativeTo(null); // biar di tengah
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNamaBayi = new javax.swing.JTextField();
        txtNamaAyah = new javax.swing.JTextField();
        txtNamaIbu = new javax.swing.JTextField();
        cmb_Kelamin = new javax.swing.JComboBox<>();
        txtTanggal = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        Btn_tampilkan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Tampilan = new javax.swing.JTextArea();

        jLabel1.setText("KELAHIRAN");

        jLabel2.setText("Nama Bayi");

        jLabel3.setText("Nama Ayah");

        jLabel4.setText("Nama Ibu");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Tanggal Kelahiran");

        jLabel7.setText("Alamat");

        cmb_Kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        cmb_Kelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_KelaminActionPerformed(evt);
            }
        });

        Btn_tampilkan.setText("Tampilkan Data");
        Btn_tampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_tampilkanActionPerformed(evt);
            }
        });

        txt_Tampilan.setColumns(20);
        txt_Tampilan.setRows(5);
        jScrollPane1.setViewportView(txt_Tampilan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_tampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(74, 74, 74)
                                    .addComponent(txtAlamat))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNamaIbu, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNamaAyah, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNamaBayi, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmb_Kelamin, 0, 187, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTanggal))))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNamaBayi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaAyah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaIbu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmb_Kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_tampilkan))
                    .addComponent(jScrollPane1))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_KelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_KelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_KelaminActionPerformed

    private void Btn_tampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_tampilkanActionPerformed
                                         
// Ambil data dari form
    String namaBayi = txtNamaBayi.getText();
    String namaAyah = txtNamaAyah.getText();
    String namaIbu  = txtNamaIbu.getText();
    String jk       = cmb_Kelamin.getSelectedItem().toString();
    String tanggal  = txtTanggal.getText();
    String alamat   = txtAlamat.getText();

    // Membuat object class Kelahiran
    Kelahiran data = new Kelahiran(
        namaBayi, namaAyah, namaIbu, jk, tanggal, alamat
    );

    // Menampilkan output menggunakan getter
    txt_Tampilan.setText(
        "Nama Bayi      : " + data.getNamaBayi() + "\n" +
        "Nama Ayah      : " + data.getNamaAyah() + "\n" +
        "Nama Ibu       : " + data.getNamaIbu() + "\n" +
        "Jenis Kelamin  : " + data.getJenisKelamin() + "\n" +
        "Tanggal Lahir  : " + data.getTanggalLahir() + "\n" +
        "Alamat         : " + data.getAlamat()
    );
} 


public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new GUI_Kelahiran().setVisible(true);
        }
    });
    }//GEN-LAST:event_Btn_tampilkanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_tampilkan;
    private javax.swing.JComboBox<String> cmb_Kelamin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNamaAyah;
    private javax.swing.JTextField txtNamaBayi;
    private javax.swing.JTextField txtNamaIbu;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextArea txt_Tampilan;
    // End of variables declaration//GEN-END:variables
}
